CREATE TABLE GM_GAMES (
    GAME_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    RELEASE_DATE DATE,
    CATEGORY BIGINT,
    STUDIO BIGINT,
    IMAGER BLOB,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
);

CREATE TABLE GM_CONTACT (
    CONTACT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    SUBJECT VARCHAR(255),
    MESSAGE VARCHAR(2),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
);

CREATE TABLE GM_DONATION (
    DONATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT,
    PAYMENT_METHOD BIGINT,
    TRANSACTION_ID BIGINT,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
);

CREATE TABLE GM_JOIN_USER_GAMES (
    JOIN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT,
    GAME_ID BIGINT,
    CREATED_BY VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP
);

CREATE TABLE GM_ROLE (
    ROLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
);

CREATE TABLE GM_USERS (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLE_ID BIGINT,
    NAME_AR VARCHAR(255),
    NAME_EN VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(25),
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR(255)
);

ALTER TABLE GM_DONATION ADD FOREIGN KEY (USER_ID) REFERENCES GM_USERS(USER_ID);

ALTER TABLE GM_JOIN_USER_GAMES ADD FOREIGN KEY (USER_ID) REFERENCES GM_USERS(USER_ID);
ALTER TABLE GM_JOIN_USER_GAMES ADD FOREIGN KEY (GAME_ID) REFERENCES GM_GAMES(GAME_ID);

ALTER TABLE GM_USERS ADD FOREIGN KEY (ROLE_ID) REFERENCES GM_ROLE(ROLE_ID);


insert into GM_ROLE (role_id,name) values (1,'Admin');
insert into GM_ROLE (role_id,name) values (2,'User');
insert into GM_USERS (USER_ID,ROLE_ID,NAME_AR,NAME_EN,EMAIL,PHONE,USERNAME,PASSWORD) values (1,1,'Admin','المسؤل','admin@gmail.com','96277','admin','123');
insert into GM_USERS (USER_ID,ROLE_ID,NAME_AR,NAME_EN,EMAIL,PHONE,USERNAME,PASSWORD) values (2,2,'User','مستخدم','User@gmail.com','96277','User','123');

INSERT INTO GM_GAMES (NAME, DESCRIPTION, RELEASE_DATE, CATEGORY, STUDIO, IMAGER, CREATED_DATE, CREATED_BY, UPDATED_DATE, UPDATED_BY)
VALUES ('SkyDrop', 'An adrenaline-pumping aerial battle game', '2025-06-15', 7, 2, FILE_READ('C:\Users\ADMIN\Desktop\games\src\main\resources\static\game1.png'), CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');

INSERT INTO GM_GAMES (NAME, DESCRIPTION, RELEASE_DATE, CATEGORY, STUDIO, IMAGER, CREATED_DATE, CREATED_BY, UPDATED_DATE, UPDATED_BY)
VALUES ('PUBG Extreme', 'A high-intensity survival shooter', '2025-07-10', 8, 3, FILE_READ('C:\Users\ADMIN\Desktop\games\src\main\resources\static\game2.png'), CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');

INSERT INTO GM_GAMES (NAME, DESCRIPTION, RELEASE_DATE, CATEGORY, STUDIO, IMAGER, CREATED_DATE, CREATED_BY, UPDATED_DATE, UPDATED_BY)
VALUES ('Fire Battle', 'Fast-paced strategy combat with endless action', '2025-05-25', 5, 4, FILE_READ('C:\Users\ADMIN\Desktop\games\src\main\resources\static\game3.png'), CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');

